import os
import discord

# Recupera il token dal secret
token = os.getenv('DISCORD_TOKEN')

# Crea una connessione al client di Discord
client = discord.Client()

@client.event
async def on_ready():
    print(f'Logged in as {client.user}')

# Esegui il bot con il token
client.run(token)
